import asyncio
from pyrogram import Client as c

API_ID = input("\nEnter Your API_ID:\n > ")
API_HASH = input("\nEnter Your API_HASH:\n > ")

print("\n\n Enter Phone number when asked.\n\n")

i = c(":memory:", api_id=API_ID, api_hash=API_HASH)

async def main():
    await i.start()
    ss = await i.export_session_string()
    xx = f"HERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n\n{ss}\n\nGENERATED BY Arch"
    ok = await i.send_message("me", xx)
    print("\nHERE IS YOUR STRING SESSION, COPY IT, DON'T SHARE!!\n")
    print(f"\n{ss}\n") 
    print("\nGENERATED BY Arch\n")
    
    # zoneyxd
    archbots_chat = await i.resolve_peer("https://t.me/archbots")
    arch_supports_chat = await i.resolve_peer("https://t.me/arch_supports")
    
    await i.join_chat(archbots_chat)
    await i.join_chat(arch_supports_chat)

asyncio.run(main())
